In [1]:
from globalvars import *
from spritesheet import *
import numpy as np
import pygame

In [1]:
class Map(object):
    
    def __init__(self):
        self.init()
        
    def init(self):
        pass
    
    def get_values(self,rect):
        raise NotImplemented
    
    def get_value(self,i,j):
        raise NotImplemented
        

In [17]:
class MapGraphic(object):
    def __init__(self,map_):
        self.map_ = map_
        self.init()
        
    def init(self):
        pass
        
    def get_image(self,rect):
        raise NotImplemented

In [11]:
class MyMap(Map):
    
    def init(self):
        ground_map = np.random.uniform(size=(MAP_SIZE,MAP_SIZE))<EARTH_DENSITY
        ground_map[:,0] = np.zeros((MAP_SIZE,))
        ground_map[:,-1] = np.zeros((MAP_SIZE,))
        ground_map[0,:] = np.zeros((MAP_SIZE,))
        ground_map[-1,:] = np.zeros((MAP_SIZE,))
        
        self.map_ = ground_map

    def get_value(self,i,j):
        return self.map_.arr[i,j]
    
    def get_values(self,rect):
        return self.map_.arr[rect[0]:rect[0]+rect[2],rect[1]:rect[1]+rect[3]]

In [33]:
class MyMap_Graphic(MapGraphic):
    def init(self):
        spritesheet = SpriteSheet("./GroundMap.png")
        self.tiler = Tiler8bit(spritesheet,N_PER_ROW,SIZE,index_dict=GROUNDMAP_TILES_DICT)
        
    def get_image(self,rect):
        temp_map = BinMap(self.map_.get_values(rect))
        return self.tiler.get_surface(temp_map)
        
        

In [27]:
pygame.init()

(6, 0)

In [29]:
screen = pygame.display.set_mode((400,300))

In [30]:
my_map = MyMap()

In [34]:
map_graphic = MyMap_Graphic(my_map)

In [35]:
screen.blit(map_graphic.get_image((0,0,10,10)),(0,0))

<rect(0, 0, 320, 300)>

In [36]:
pygame.display.flip()

In [20]:
Tiler8bit?

In [19]:
SpriteSheet?

In [21]:
import globalvars

In [22]:
spritesheet = SpriteSheet("./GroundMap.png")
tiler = Tiler8bit(spritesheet,N_PER_ROW,SIZE,index_dict=GROUNDMAP_TILES_DICT)

('Unable to load spritesheet image: ', './GroundMap.png')


SystemExit: cannot convert without pygame.display initialized

To exit: use 'exit', 'quit', or Ctrl-D.


In [37]:
MAP_SIZE

30

In [17]:
arr = np.random.randint(0,2,size=(100,100))

In [10]:
kernel = np.array([[0,2,0],[2,4,2],[0,2,0]])

In [39]:
kernel

array([[0, 2, 0],
       [2, 4, 2],
       [0, 2, 0]])

In [43]:
arr[:5,:5]

array([[1, 1, 0, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1]])

In [13]:
np.convolve(arr,kernel)

ValueError: object too deep for desired array

In [14]:
from scipy import signal

In [48]:
signal.convolve2d(arr,kernel,mode='same')[:5,:5]

array([[ 8,  6,  4,  6,  6],
       [ 8,  6,  2,  4,  6],
       [ 8,  8,  8, 10,  6],
       [ 4,  2,  4,  8,  6],
       [ 6,  4,  4,  8,  8]])

In [50]:
signal.convolve2d?

In [18]:
%timeit signal.convolve2d(arr,kernel)

1000 loops, best of 3: 325 µs per loop


In [ ]:
kernel = np.array([
    []
    ])

In [30]:
def calc_ss_index(nw,n,ne,w,center,e,sw,s,se):
        if not center:
            return -1
        vals = [
            (nw&n&w)<<0,
            n<<1,
            (ne&n&e)<<2,
            w<<3,
            e<<4,
            (sw&s&w)<<5,
            s<<6,
            (se&s&e)<<7
        ]
        return sum(vals)

In [22]:
i,j = 6,6
calc_ss_index(arr[i,j],*)

SyntaxError: invalid syntax (<ipython-input-22-d5602d5f74c0>, line 2)

In [34]:
i,j = 6,7

In [35]:
arr[i-1:i+2,j-1:j+2]

array([[1, 0, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [36]:
calc_ss_index(*arr[i-1:i+2,j-1:j+2].flatten())

64

In [51]:
arr.strides

(800, 8)

In [52]:
arr.shape

(100, 100)

In [ ]:
np.a

In [55]:
arr2 = np.arange(20)

In [56]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
arr2.strides

(8,)

In [53]:
from numpy.lib.stride_tricks import as_strided
def running_average_strides(seq, window=100):
    stride = seq.strides[0]
    sequence_strides = as_strided(seq, shape=[len(seq) - window + 1, window], strides=[stride, stride])
    return sequence_strides.mean(axis=1)

In [58]:
def rolling_window_strides(seq, window=5):
    stride = seq.strides[0]
    sequence_strides = as_strided(seq, shape=[len(seq) - window + 1, window], strides=[stride, stride])
    return sequence_strides

In [59]:
rolling_window_strides(arr2)

array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13],
       [10, 11, 12, 13, 14],
       [11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16],
       [13, 14, 15, 16, 17],
       [14, 15, 16, 17, 18],
       [15, 16, 17, 18, 19]])

In [60]:
def rolling_window_2d_strides(seq, window=5):
    stride0 = seq.strides[0]
    stride1 = seq.strides[1]
    sequence_strides = as_strided(seq, shape=[len(seq) - window + 1, window], strides=[stride, stride])
    return sequence_strides

In [75]:
arr[:10,:10]

array([[1, 1, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0]])

In [137]:
kernel_nw = np.array([
        [0,0,0],
        [0,0,1],
        [0,1,1]
    ])
kernel_ne = np.array([
        [0,0,0],
        [1,0,0],
        [1,1,0]
    ])
kernel_sw = np.array([
        [0,1,1],
        [0,0,1],
        [0,0,0]
    ])
kernel_se = np.array([
        [1,1,0],
        [1,0,0],
        [0,0,0]
    ])
kernel_cards = np.array([
        [0,64,0],
        [16,0,8],
        [0,2,0]
    ])

def conv_corner(arr,kernel):
    return (signal.convolve2d(arr,kernel_ne,mode='same')==3).astype(int) 

def conv(arr,kernel):
    return signal.convolve2d(arr,kernel,mode='same')

def process_arr(arr):
    conv_ne = conv_corner(arr,kernel_ne)
    conv_nw = conv_corner(arr,kernel_nw)
    conv_se = conv_corner(arr,kernel_se)
    conv_sw = conv_corner(arr,kernel_sw)
    conv_cards = conv(arr,kernel_cards)
    return (conv_cards + conv_nw + 4*conv_ne + 32*conv_sw + 128*conv_se)*arr+(1-arr)*-1

In [76]:
(signal.convolve2d(arr,kernel_ne,mode='same')==3).astype(int)[:10,:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [85]:
arr

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       ..., 
       [0, 0, 1, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 1, 0]])

In [98]:
calc_ss_index(*arr[i-1:i+2,j-1:j+2].flatten())

64

In [96]:
process_arr(arr[i-1:i+2,j-1:j+2])

array([[0, 1, 0],
       [2, 1, 1],
       [2, 2, 0]])

In [97]:
arr[i-1:i+2,j-1:j+2]

array([[1, 0, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [107]:
conv(arr[i-1:i+2,j-1:j+2],kernel_cards)

array([[ 0, 88,  0],
       [82, 64, 74],
       [16, 26,  8]])