In [1]:
import marching_squares
import numpy as np
import pygame
import spritesheet
from scipy.ndimage.filters import gaussian_filter

In [2]:
pygame.init()
screen = pygame.display.set_mode((1000,1000))

In [3]:
ss = spritesheet.SpriteSheet("./marching-tiles-large.png")

In [4]:
tiler = marching_squares.MarchingSquaresTiler(ss,0,32)

In [5]:
map_size = 32

In [6]:
arr = np.random.uniform(0,1,size=(map_size,map_size))

In [7]:
arr = gaussian_filter(arr,sigma=2)

In [8]:
arr = (arr-arr.min())/(arr.max()-arr.min())

In [9]:
arr = (arr*7).astype(int)

In [10]:
surface = tiler.get_surface(arr)

In [11]:
screen.blit(surface,(0,0))

<rect(0, 0, 1000, 1000)>

In [12]:
pygame.display.flip()

In [13]:
arr

array([[1, 1, 1, ..., 3, 3, 4],
       [1, 1, 2, ..., 3, 3, 4],
       [1, 1, 2, ..., 3, 3, 4],
       ..., 
       [2, 2, 1, ..., 3, 4, 4],
       [2, 1, 0, ..., 3, 3, 3],
       [1, 1, 0, ..., 3, 3, 2]])

In [14]:
16*15

240

In [15]:
12*15

180

In [16]:
arr

array([[1, 1, 1, ..., 3, 3, 4],
       [1, 1, 2, ..., 3, 3, 4],
       [1, 1, 2, ..., 3, 3, 4],
       ..., 
       [2, 2, 1, ..., 3, 4, 4],
       [2, 1, 0, ..., 3, 3, 3],
       [1, 1, 0, ..., 3, 3, 2]])

In [17]:
arr

array([[1, 1, 1, ..., 3, 3, 4],
       [1, 1, 2, ..., 3, 3, 4],
       [1, 1, 2, ..., 3, 3, 4],
       ..., 
       [2, 2, 1, ..., 3, 4, 4],
       [2, 1, 0, ..., 3, 3, 3],
       [1, 1, 0, ..., 3, 3, 2]])

In [18]:
64*32

2048